### ISSUE TITLE
Convert the project to a static page by Docsify 

### ISSUE THREAD

**Issue by wjsvec** [summer-ospp/ospp-event-resources#14]
Thanks for @LinuxSuRen ‘s suggestion.

**Comment by wjsvec** [comment]
I'm not very familiar with golang so I used docsify instead.

I don’t have enough permissions for this repo. You can take a look at the specific effects in my fork.

https://wjsvec.github.io/ospp-event-resources/#/bupt

**Comment by LinuxSuRen** [comment]
I don't have permission either. By the way, you don't need to know anything about Golang when using Hugo. It is just a template tech.

**Comment by jimmieme** [comment]
@LiMeng00 @LinuxSuRen If need, permissions could and should be assigned to more members. I think it's time to update the permission settings of Summer-OSPP Github group.

cc @yinjiayi

**Comment by LinuxSuRen** [comment]
Having more active members will be helpful for OSPP.

**Comment by LinuxSuRen** [comment]
Thank you @jianminww for the member invitation.

**Comment by jimmieme** [comment]
> Thank you @jianminww for the member invitation.

@LinuxSuRen @wjsvec Thank you for your continuous contribution on Summer-OSPP.

I have created a team @summer-ospp/community to be capable of managing main repositories. @LiMeng00 could manage and expand the members of @summer-ospp/community . I think we could use this team as community of Summer-OSPP and run this program as a community.

**Comment by wjsvec** [comment]
> > Thank you @jianminww for the member invitation.
> 
> @LinuxSuRen @wjsvec Thank you for your continuous contribution on Summer-OSPP.
> 
> I have created a team @summer-ospp/community to be capable of managing main repositories. @LiMeng00 could manage and expand the members of @summer-ospp/community . I think we could use this team as community of Summer-OSPP and run this program as a community.

Thanks a lot!🥳

**Comment by LinuxSuRen** [comment]
> I think we could use this team as community of Summer-OSPP and run this program as a community.

This is really cool. For the further consideration, we could even propose a procedure that who could join the team. For example:

* A current active member sends a nominate on GitHub issue
  * List the contributions from the new potential member
* At least thumb-up from other members
* Welcome the new member

**Comment by jimmieme** [comment]
> > I think we could use this team as community of Summer-OSPP and run this program as a community.
> 
> This is really cool. For the further consideration, we could even propose a procedure that who could join the team. For example:
> 
> * A current active member sends a nominate on GitHub issue
>   
>   * List the contributions from the new potential member
> * At least thumb-up from other members
> * Welcome the new member

I totally agree with this procedure.

**Comment by wjsvec** [comment]
Here is a ToDo lists about static webpage  from @LinuxSuRen 's suggestion

- [ ] Topic(with PDF show), Presenter(If willing to leave a social media account)

- [ ] Event photos and group photos

- [ ] Event date

**Comment by LinuxSuRen** [comment]
Consider the initial status of the static web page is done. We could close this issue then track these suggestion is a new one.
