### ISSUE TITLE
可否增加一个放置分享PPT的文件夹

### ISSUE THREAD

**Issue by wjsvec** [summer-ospp/ospp-event-resources#2]
这可能会很有用

**Comment by LinuxSuRen** [comment]
建议把PPT上传到专门的网站，例如：Google Doc、腾讯文档中，这样的话，大家能直接在线打开，也能避免当前仓库过大。最后把PPT链接给到这里即可。

**Comment by HungryFish034** [comment]
【腾讯文档】Fish*🐡 分享给你多个文件 https://docs.qq.com/s/geK3GDQhY3r78xxzXEvo6a 密码：uTxvlq

后续补充文件
